---
# easy Ubuntu nginx playbook as an example.
- hosts: stunable:&dev
  user: ubuntu 
  sudo: True

  vars:
     #workers: use at template ansible_processor_count 
     connections : "1024"
     is_10_up: "'$ansible_distribution_version' >= '10.04'"
     is_ubuntu: "'$ansible_distribution' == 'Ubuntu'"
     app_name: "dev.stunable.com"
     app_db_name: "dev_stunable_db"
     app_port: 8080
     project_root: /home/ubuntu/$app_name
     repo: git@github.com:Stunable/stella_site.git
     repo_branch: carouselRevision
     manage_path: $project_root/project/
     project_user: ubuntu
     static_path: static
     media_path: media
     postgres_host: 10.111.23.94
     redis_db_number: 3

  vars_files:
     - sec/passwords.yml

  tasks:
     - include: server_setup/tasks/add-people.yml 
     - include: nginx/tasks/nginx-task.yml
     - include: server_setup/tasks/install-app.yml
     - include: postgres/tasks/setup-postgres-app-task.yml
     - include: server_setup/tasks/update-app.yml

  handlers:
     - name: restart nginx
       action: service name=nginx state=restarted


# alter table racks_item alter column featured_image_id type integer using (featured_image_id::integer); 