---
# easy Ubuntu nginx playbook as an example.
- hosts: stunable
  user: ubuntu 
  sudo: True

  vars:
     #workers: use at template ansible_processor_count 
     connections : "1024"
     app_name: "stunable.com"
     app_pw: "stunable!!!"
     app_port: 8099
     project_root: "/home/ubuntu/{{app_name}}"
     repo: git@github.com:Stunable/stella_site.git
     repo_version: 2015
     manage_path: "{{project_root}}/project/"
     project_user: ubuntu
     static_path: static
     media_path: media
     db_user: stunable
     db_host: damondb2.crqx3azsna3d.us-east-1.rds.amazonaws.com
     db_name: stunable_db
     redis_db_number: 3
     hx_log_dir: /var/log/hendrix/
     hendrix_opts: "--http_port {{app_port}} --settings settings --log {{hx_log_dir}}{{app_name}}.log"


  # vars_files:
  #    - sec/passwords.yml

  tasks:
     - include: server_setup/tasks/add-people.yml 
     # - include: nginx/tasks/nginx-task.yml
     - include: server_setup/tasks/install-app.yml
     - include: postgres/tasks/setup-postgres-app-task.yml
     - include: server_setup/tasks/update-app.yml

  handlers:
     - name: restart nginx
       action: service name=nginx state=restarted


# alter table racks_item alter column featured_image_id type integer using (featured_image_id::integer); 