  - name: git clone
    action: git repo={{repo}} dest={{project_root}}/project version={{repo_version}}
    sudo_user: ubuntu

  - name: install python libraries
    pip: requirements={{project_root}}/project/requirements.txt virtualenv={{project_root}}

  - name: link admin media
    file:  dest={{project_root}}/project/{{static_path}}/admin src={{project_root}}/lib/python2.7/site-packages/django/contrib/admin/static/ state=link
    sudo_user: ubuntu

  - name: write gunicorn conf
    action: template src='server_setup/templates/gunicorn.conf.py.j2' dest={{manage_path}}/gunicorn.conf.py

  - name: write local_settings
    action: template src='server_setup/templates/local_settings.py.j2' dest={{manage_path}}/local_settings.py

  - name: syncdb
    django_manage: command=syncdb app_path={{manage_path}} virtualenv={{project_root}}
    sudo_user: ubuntu 

  - name: migrate
    django_manage: command=migrate app_path={{manage_path}} virtualenv={{project_root}}
    sudo_user: ubuntu

  - name: Create hendrix log location
    file:
      path="{{hx_log_dir}}"
      state=directory
      owner="ubuntu"
    sudo: yes
    sudo_user: root

  - name: Add hendrix upstart conf
    template: src=hendrix-upstart.conf.j2 dest=/etc/init/hendrix.conf mode=0751
    sudo: yes
    sudo_user: root

  - name: Start hendrix
    service:
      name="hendrix"
      state=restarted
    sudo: yes
    sudo_user: root

  - name: restart nginx 
    service: name=nginx state=restarted 


